pipeline {
    agent any

    stages {
        stage('Install Dependencies') {
            steps {
                dir('Desktop/DevOps/registration form') {
                    bat '"C:\\Users\\Shlok Anand\\AppData\\Local\\Programs\\Python\\Python313\\python.exe" -m pip install -r requirements.txt'
                }
            }
        }

        stage('Run Test') {
            steps {
                dir('Desktop/DevOps/registration form') {
                    bat '"C:\\Users\\Shlok Anand\\AppData\\Local\\Programs\\Python\\Python313\\python.exe" test_form.py'
                }
            }
        }
    }
}
